### ISSUE TITLE
SSL libraries not available for windows

### ISSUE THREAD

**Issue by parduino** [NHERI-SimCenter/AgaveExplorer#13]
Hi Guys,

   When trying to compile the Agave interface in windows it has problems finding SSL related libraries (that do not come with QT windows distribution). To run in windows these libraries must be added and the project file modified to include them.

**Comment by psempoli** [comment]
This has been an ongoing question.

SSL comes standard on all Mac and all (for all practical purposes) Linux.

For windows it is strange.  Most machines which I have attempted to run things have SSL already, but not all.

I am still trying to find a pattern as to what doesn't have it. 

Incorporating SSL involves a significant set of technical and legal issues, and is not straightforward.

**Comment by psempoli** [comment]
DO NOT attempt to link SSL libraries directly to a Qt app via the project file. It does not work that way.

**Comment by psempoli** [comment]
The following is recorded for my future reference:
https://wiki.openssl.org/index.php/Binaries

**Comment by psempoli** [comment]
Most likely, we will have to provide a .dll to be included in the installed folder. Probably doable technically, if a little delicate.

Legal questions may have been simplified by SSL's recent license change. Will have to review.

**Comment by parduino** [comment]
A .dll ir .lib. The libraries are freely available through OpenSSL. I mean the .pro file should just indicate where these libs are (can be the same folder indicated by the installer)

So, you have compiled the QT Agave project in Windows without it complaining for SSL??

Thanks

Pedro

Sent from my iPhone

On Aug 24, 2017, at 8:30 PM, psempoli <notifications@github.com<mailto:notifications@github.com>> wrote:


Most likely, we will have to provide a .dll to be included in the installed folder. Probably doable technically, if a little delicate.

Legal questions may have been simplified by SSL's recent license change. Will have to review.

**Comment by psempoli** [comment]
Usually Qt doesn't complain at all about SSL. I had to write the error message so it would complain, instead of simply refusing to connect without explaining why.

See: http://doc.qt.io/qt-5/ssl.html#import-and-export-restrictions

There are significant legal concerns in making publicly available OpenSSL in the US. That is, posting such code on-line (can) count as exporting it, which is subject to some rather strict (dumb) regulations. See: https://www.bis.doc.gov/index.php/documents/regulations-docs/federal-register-notices/federal-register-2014/951-ccl5-pt2/file So, DO NOT upload any part of SSL to these git repos.

From a technical side, this is easy. It is sufficient that the 2 relevant dll are found. During development they can be in the lib folder of the Qt version that you are compiling for. In fact, that is what I would suggest you try first. Find the two dll at: https://indy.fulgan.com/SSL/openssl-1.0.2l-x64_86-win64.zip, put them in the lib folder of the version of qt you are building against. It should work.

As for actual deployment, the technical side is also easy. The two dll must be in the relevant folder. The .pro file does not dictate the contents of the install package, it provides instructions to the compiler, but I have scripts which setup install packages and can place the 2 .dll in the right place.

Since most machines have SSL, the legal questions of us distributing it did not seem to be a high priority for me.

**Comment by psempoli** [comment]
I was hoping we could avoid the legal questions by not touching the actual SSL code or binaries at all.

**Comment by psempoli** [comment]
If this were solely a technical issue, I could solve it, very quickly, by adding the two .dll to the installer creation script. But I have not done that, since that may be illegal.

**Comment by psempoli** [comment]
Or, to be more precise: Not so much illegal, but subject to obtuse reporting requirements.

**Comment by psempoli** [comment]
These laws have also changed significantly since I started college, which adds to complications researching the matter.

**Comment by parduino** [comment]
Peter

Sure, don't worry we will find a way out that is legally correct. Just thought this could be a good case to provide info to possible users trying to develop agave apps using QT. It was also interesting just from my personal learning on the use of SSL.
Thanks for getting back to me

Pedro

Sent from my iPhone

On Aug 25, 2017, at 12:16 AM, psempoli <notifications@github.com<mailto:notifications@github.com>> wrote:


These laws have also changed significantly since I started college, which adds to complications researching the matter.

**Comment by psempoli** [comment]
Historically, a lot of this is a legacy of the cold war, during which cryptographic info was very tightly controlled against export, (but not import or use), which is why we can download it no problem. Moreover, personnel with knowledge of cryptography were subject to some rules as well.

This caused some problems when the Internet gradually became more ubiquitous. In the early days of the Internet, Netscape was released with two version: a "US" version and an "exportable" international version. The US version having stronger HTTPS.

Today, the rules have loosened considerably, but exports of crypto are still monitored. (And, again, I think it is more the personnel than that software these days that the feds are worried about.)

Of course, this leads to a lot of dumb reporting rules. See: http://www.apache.org/licenses/exports/ for an example of how one group deals with it.

(I neglected to mention certain other countries, like China, have laws about importing crypto as well. Also, the licensing of OpenSSL, while open source, is a bit obtuse, but they have been changing that.)

**Comment by psempoli** [comment]
I hasten to add that there is a minor technical reason that we would want to avoid packaging OpenSSL as well. OpenSSL is frequently updated, and sometimes for very important reasons, we would have trouble keeping up with them.

**Comment by psempoli** [comment]
For now, I think I will make the error message more descriptive, to encourage the user to download the needed files themselves and explain how.

**Comment by psempoli** [comment]
Ported Planning Paradigm
